language: ruby
before_script:
  - mysql -e 'create database detached_counter_cache;'
rvm:
  - 2.3
  - 2.2
  - 2.1
gemfile:
  - gemfiles/Gemfile-4-1
  - gemfiles/Gemfile-4-2
  - gemfiles/Gemfile-5-0
  - gemfiles/Gemfile-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-5-0
    - gemfile: gemfiles/Gemfile-edge
